### ISSUE TITLE
Kube Config Context Without a Namespace Causes Error

### ISSUE THREAD

**Issue by emmercm** [so0k/powerline-kubernetes#13]
I have a kubeconfig that looks like:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: ...
  name: ...
contexts:
- context:
    cluster: ...
    user: ...
  name: ...
current-context: ...
kind: Config
preferences: {}
users:
- name: ...
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - ...
      command: ...
      env:
        - name: ...
          value: ...
```

and when I `powerline-daemon --kill` I get an error similar to:

```
2019-12-03 10:15:52,043:ERROR:shell:kubernetes:'namespace'
```

I think https://github.com/so0k/powerline-kubernetes/commit/c366a55de5527bf9fa9067697771fd80466fe153#diff-5206fb189568a38aa689ef479153c15d intended to fix this but there's two instances of `namespace = ctx['namespace']`.
